### ISSUE TITLE
Provides whitelisting mode

### ISSUE THREAD

**Issue by chenmaoran** [husjon/obsidian-file-cleaner-redux#25]
All my attachments (images, PDFs, office files, etc.) are stored in one directory, and only need to clean up attachments in this one folder. Is it possible to provide a whitelist mode instead of an excluded folder mode?

**Comment by husjon** [comment]
Hi, this should indeed be possible.

I remember this was requested in the original plugin as well.
https://github.com/Johnson0907/obsidian-file-cleaner/issues/11

I'm going to think about the implementation details over the weekend and get back to you.

**Comment by husjon** [comment]
@chenmaoran this has now been implemented and is available in version 0.8.0
