### ISSUE TITLE
Determine folders that will be empty after cleanup, and clean those up too

### ISSUE THREAD

**Issue by owbosh** [husjon/obsidian-file-cleaner-redux#30]
Sometimes, after a cleanup, empty folders are left laying around, which requires a second cleanup to remove. Would it be possible to clean everything in one go by figuring out which folders will be empty after the 'first pass' cleanup, and clean those too?

**Comment by husjon** [comment]
Hi, for somewhat reason I didn't get the notification about this issue but yes it is on my list of improvements. :)

**Comment by husjon** [comment]
@owbosh Just a heads up that I am rewriting the plugin and this will be supported in v1.0.0

I do not have a release date yet but I'm hoping it will be very soon.

**Comment by husjon** [comment]
I'm in the process of releasing v1.0.0 so I'll go ahead and close the issue.

Please don't hesitate open a new if another issue should arise. :)
