### ISSUE TITLE
The plugin try to remove file type not in the defined types

### ISSUE THREAD

**Issue by dudukk1312** [husjon/obsidian-file-cleaner-redux#34]
Hello,

When I run the File clean command, it tried to delete the file type that not define in the attachment file types. 
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/33556384/b714d8d6-5352-44af-8122-ec82ea780599)
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/33556384/65836933-609c-4029-a9dc-6349457e7951)
I want to keep the .mdenc files.

Another suggestion, could you support the wildcard syntax in exclude/include folder? I have many folder `attachments` in different folders in my Vault

Thank you

**Comment by husjon** [comment]
Hi and thanks for raising the issue, I'll have a look at this in the next couple of days should be a rather easy fix.

As for the suggestion, I really like the idea but needs some thinking, could you create a separate issue for that so it can be tracked in isolation? Thanks :)
