### ISSUE TITLE
On boot up, plugin suggests deleting "/".

### ISSUE THREAD

**Issue by johnnynalley** [husjon/obsidian-file-cleaner-redux#37]
OS: iOS 17.3.1
Obsidian Version: 1.4.16
File-Cleaner-Redux Version: 0.8.3

Occasionally during Obsidian boot-up, the plugin will show a prompt asking if I want to clean "/". Usually, it'll say "/empty_file_1", "/empty_file_2", but I believe that it is asking if I want to delete the entirety of my root folder.

I have not tried to see what happens when I allow it to do so, and I have not been able to consistently reproduce this. It appears it only happens whenever I have multiple apps running at the same time as Obsidian, because I only notice this when Obsidian is slow to boot.

Anybody else experienced the same thing?

**Comment by husjon** [comment]
Hmm thanks for raising the issue.
It should definitely not try to delete the root vault folder.
It might be related to vault size and/or plugin load times but I need some more information to work with.

Do you have an overview of what the size of your vault is (amount of files / folders and disk usage).
Also, do you use a lot of other plugins?

I should add in some debug logging that could be toggled on to help look into different issues.

**Comment by johnnynalley** [comment]
Hello,I have 126 files with 13 folders at 50.7 MB. At the moment, I have 23 plugins installed. When it happens again, I’ll be sure to grab a screenshot.On Feb 16, 2024, at 7:06 AM, Jon Erling Hustadnes ***@***.***> wrote:﻿
Hmm thanks for raising the issue.
It should definitely not try to delete the root vault folder.
It might be related to vault size and/or plugin load times but I need some more information to work with.
Do you have an overview of what the size of your vault is (amount of files / folders and disk usage).
Also, do you use a lot of other plugins?
I should add in some debug logging that could be toggled on to help look into different issues.

**Comment by husjon** [comment]
Hi @johnnynalley, I've just pushed v0.8.4 which enables some debug logging for files and folders that are added to the cleanup cycle.

If you do see this happen again, you can now open the Obsidian Developer Console (using `Ctrl+Shift+i` / `Cmd+Shift+i`)

You should then see something along the lines of the following when enabling the Verbose level (see top-right).
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/554229/c01181d7-a1eb-44ab-abef-ac1e9eec19c4)
This is an example using my development vault but should give you an indication of how it would look

**Comment by johnnynalley** [comment]
Thank you!! It hasn't happened again in a few days at this point, but if it happens again, I'll certainly take a look.

**Comment by johnnynalley** [comment]
Okay, so it did it again. I'm not at my PC right now so unfortunately I can't pull up the logs...

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/8839930f-2e7a-4b46-b4fd-8466fe66ad3e)

**Comment by husjon** [comment]
Thanks for the update, annoying that it happened on the phone.
I tried searching to see if it was possible to get the development console on the phone, but it does not seem like it's possible.

I might need to make a test build for you which logs to a file instead.
Here's hoping that it'll happen again soon (sounds weird) on your PC :)

**Comment by johnnynalley** [comment]
I'm open to testing a new build. At this point, it does it every time I start Obsidian. I had to turn off the option to clean folders to stop it.

**Comment by husjon** [comment]
Does it do it every time on the phone, or the PC as well?

**Comment by johnnynalley** [comment]
I'm at my PC now. It does it every time on the PC and on iOS. Here is what the console logs look like: 

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/9d106403-cfee-4761-baa3-01e11abef372)

Let me know if there is anything else I can do to assist.

**Comment by johnnynalley** [comment]
And here is it prompting me to delete the root folder on desktop:

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/0fda3cb8-0fb4-4d88-8393-3d282be58aa1)

**Comment by husjon** [comment]
Thanks for the quick feedback, could you expand the listing under `Folders:`

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/554229/d3a9ab96-60fe-4b52-91dd-da48d086626d)

**Comment by johnnynalley** [comment]
Here ya go:

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/9f4c5210-027b-439f-8e68-28914ef6dd90)

**Comment by husjon** [comment]
Thanks, and just so that I have something to try to replicate, what are the current settings for the plugin?

Also, if you were to create a new vault with just this plugin using the same settings, do you still see the same result?

**Comment by johnnynalley** [comment]
Oddly enough it works as expected in the new vault.

Settings (Same for both vaults):

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/e07c58e7-4ed4-4091-adc0-d8eeaf9a9439)

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/f621c5d5-696f-436d-bf32-c1681aa8723b)

Deletion prompt in new vault:

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/72593738/4c599b11-5b67-46cc-ba30-1ac9935211a0)

**Comment by johnnynalley** [comment]
Well I deleted and reinstalled the plugin and it seems to have fixed it. All of my settings are the exact same as before. I'm going to keep the "show confirmation" setting on because if it decides to happen again I don't want my root folder deleted.

**Comment by husjon** [comment]
Glad that reinstalling it worked and yeah definitely keep the "show confirmation" option on.
I might still add a check for the root path and skip it if found, so that it cannot happen again.

I'll leave the issue open for a while longer in case you should see it again.

**Comment by husjon** [comment]
I've prepared a pull request which should fix this.
It adds a guard clause so that it explicitly filters out the root folder.

**Comment by johnnynalley** [comment]
Thank you so much!!
