### ISSUE TITLE
Canvas are detected as empty and deleted if ".*" is set in the attachment extensions option

### ISSUE THREAD

**Issue by loredfir** [husjon/obsidian-file-cleaner-redux#46]
Hi

If in the attachment extensions setting is set ".*", canvas are deleted also if not empty

version installed: 0.8.6

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/12549879/967a8f1f-6cf6-4fb6-a24c-21d4a90ae1e6)

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/12549879/09d5b6a8-d6d8-4305-ac75-fcceafd4959a)

Thanks

**Comment by husjon** [comment]
Hi @loredfir, sorry for the delay, I've now prepared a fix for this and it will be available in the next update.

This issue will be closed when I merge the fix but do feel free to either comment here / re-open if you should see the issue again.
