### ISSUE TITLE
默认只能删除图片，支持所有附件

### ISSUE THREAD

**Issue by czcn** [husjon/obsidian-file-cleaner-redux#5]
默认只能删除图片，修改一下支持所有附件（除md扩展名外的文件）
修改插件的`main.js`的以下三处
```diff
let files = app.vault.getFiles();
-  const attachmentRegex = /(.jpg|.jpeg|.png|.gif|.svg|.pdf)$/i;
+  const attachmentRegex = /(.md)$/i;
  let attachments = [];
  for (let file of files) {
-   if (file.name.match(attachmentRegex)) {
+   if (!file.name.match(attachmentRegex)) {
      attachments.push(file);
    }
  }
  let usedAttachments = [];
  let resolvedLinks = app.metadataCache.resolvedLinks;
  if (resolvedLinks) {
    for (const [mdFile, links] of Object.entries(resolvedLinks)) {
      for (const [path, times] of Object.entries(resolvedLinks[mdFile])) {
-        let attachmentMatch = path.match(attachmentRegex);
+        let attachmentMatch = !path.match(attachmentRegex);
        if (attachmentMatch) {
```

**Comment by husjon** [comment]
By using this version of the plugin, this can now be done from within Settings, see [Readme.md#plugins-settings-showing-default-values](https://github.com/husjon/obsidian-file-cleaner/tree/main?tab=readme-ov-file#plugins-settings-showing-default-values).

The plugin is not yet in the Obsidian Community Plugins repository, but I'm hoping to do that very soon.

In the meanwhile you can download it from Releases and install it manually under the `<ObsidianVault>/.obsidian/plugins` folder.

https://github.com/husjon/obsidian-file-cleaner/releases/tag/0.2.3

Hope this helps.

**Comment by husjon** [comment]
Hi @czcn 

File Cleaner Redux has now been added to the Obsidian Plugin Repository.
You can find the plugin here: https://obsidian.md/plugins?search=File%20Cleaner%20Redux
Alternative, the following can be used to install it in Obsidian directly: https://obsidian.md/plugins?id=file-cleaner-redux

I will close this issue as the mentioned issue has been fixed.
