### ISSUE TITLE
"No file to clean".  User error?

### ISSUE THREAD

**Issue by jimmyfitz** [husjon/obsidian-file-cleaner-redux#50]
I have only just installed this plugin so it's entirely possible I'm doing something wrong.

Very easy to replicate behaviour though.  I have a number of images that are no longer backlinked.  I can confirm this in Obsidian, however no matter where I am when I click "Clean files" I just get a little message in the top right saying "No file to clean".
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/35523454/175b0a4f-e93a-4e80-9f8d-5cad9a022aeb)

**Comment by husjon** [comment]
Hi, have you set the extensions for these images / files in the plugin setting?

Screenshot for reference
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/554229/246f26d5-1fea-414e-94df-a27102c2bd3a)

**Comment by jimmyfitz** [comment]
Sigh. I misinterpreted that to be if you wanted to filter the tool. User error it is.  Having now entered extentsion info it's working fine. Apologies.

**Comment by husjon** [comment]
No worries, things like this can easily be missed, glad you figured it out.

The settings for the plugin has been do as little as possible by default and let the user choose what they need. :slightly_smiling_face:
