### ISSUE TITLE
My unused file not clean( plugins not work!)

### ISSUE THREAD

**Issue by brucexiaok** [husjon/obsidian-file-cleaner-redux#59]
In my Obsidian, the plugin seems not working
I put all pasted image to attachment folder called “附件”
but when I delete link from note , the plugin can not find the unused file shows "No file to clean"

but I tried this https://github.com/Johnson0907/obsidian-file-cleaner , it work fine for me 

https://github.com/husjon/obsidian-file-cleaner-redux/assets/10465523/62bdd974-69df-4967-b60c-0a1651d5c7bf

**Comment by brucexiaok** [comment]
https://github.com/Johnson0907/obsidian-file-cleaner 
this work fine for me 

https://github.com/husjon/obsidian-file-cleaner-redux/assets/10465523/b99e30c0-21ad-4273-8110-e0e748777527

**Comment by husjon** [comment]
Hi, I suspect that you might have forgotten to set which extensions should be cleaned up. :)
Have a look in the settings for the plugin and you can decide which kinds of files should be removed.

![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/554229/61a55c81-3641-4db2-a336-298e8cb1a3c3)


Hope this helps.

**Comment by brucexiaok** [comment]
Yes! that's the problem, Thanks!
