### ISSUE TITLE
Can not delete file changed by obsidian-attachment-name-formatting

### ISSUE THREAD

**Issue by 3fok** [husjon/obsidian-file-cleaner-redux#60]
When I use [changed by obsidian-attachment-name-formatting](https://github.com/JYC333/obsidian-attachment-name-formatting), it changes the name of unused files to tmp... However, your plugin does not delete those files. 
![image](https://github.com/husjon/obsidian-file-cleaner-redux/assets/62346540/34f6c850-8934-4b97-a98f-998cb46868e3)
But when I use [obsidian-file-cleaner](https://github.com/Johnson0907/obsidian-file-cleaner), it can delete them. 

I don't know why this happens. Can you check it? :((

**Comment by husjon** [comment]
Hi, the only reason why these files should not be picked up as far as I can tell from the image is either:
* `png` files are not added to the list of extensions that should be cleaned up (see: **Included attachment extensions** in settings). 
* The `README` folder is either added to the **Excluded Folders** or it is not part of the **Included Folders** list

Hope this helps. :slightly_smiling_face:
