### ISSUE TITLE
Default Setting, Nothing Happen

### ISSUE THREAD

**Issue by JinLong369** [husjon/obsidian-file-cleaner-redux#67]
Obsidian v1.4.16
File Cleaner Redux v1.0.2

Click "Clean files" button, and nothing happen.

Console show this:
![image](https://github.com/user-attachments/assets/8e4b9991-0a64-47fb-a54f-1e5b6c25f8f1)

![image](https://github.com/user-attachments/assets/b236265a-bb8f-46f1-91e7-efa346d9c60b)

**Comment by husjon** [comment]
Hmm, strange.
Are you by chance on Windows?

**Comment by JinLong369** [comment]
Yes, windows10

**Comment by husjon** [comment]
Cool, I don't use windows myself but I can spin up a virtual machine to do some testing.
I do have a suspicion about what the issue is so it should be rather quick to fix if so.

I'll update once I've had a look.

**Comment by JinLong369** [comment]
Hello! I reinstalled version Obsidian v1.4.16, then opened the sandbox repository, and installed File Cleaner Redux v1.1.0 in it, but it still reports this error:
![image](https://github.com/user-attachments/assets/f25b443c-4f85-40a4-a107-55495033a0e9)

**Comment by JinLong369** [comment]
Maybe it's because of the Obsidian version? The 1.4.16 version doesn't have that API？

**Comment by husjon** [comment]
Yeah that is most likely it, the current version of Obsidian is 1.6.7.
1.4.16 is from October of 2023. :)
