### ISSUE TITLE
Excluded folders include them instead of exclude

### ISSUE THREAD

**Issue by Erallie** [husjon/obsidian-file-cleaner-redux#69]
When I set **Excluded folders** to a folder, it _includes_ those folders instead of excluding it. Only files from those folders are deleted, even though those are the folders that _shouldn't_ being included.

**Comment by husjon** [comment]
Hi and thanks for raising the issue, I'm not able to replicate the issue myself.
Just to confirm, you are on version `1.1.1`?
Also, would you be able to supply the `data.json` file for the plugin?

In the root of your Vault, you should find a folder called `.obsidian`.
The full path from within your vault: `.obsidian/plugins/file-cleaner-redux/data.json`.
It will contain the state of the settings of the plugin.

This will let me be able to check which settings are enabled and then I should be able to replicate it.

Thanks in advance.

**Comment by Erallie** [comment]
@husjon I was using the plugin on my phone, so I don't know how to get the `data.json` files, but for some reason, I'm not having the issue anymore... I don't know what changed. It's working fine now!

**Comment by husjon** [comment]
Aha, no worries, glad to see it resolved itself. :)

I'll close the issue but please do not hesitate to open another if a similar issues should arise.
