### ISSUE TITLE
[FR] automatically delete trash files older than X days

### ISSUE THREAD

**Issue by huyz** [husjon/obsidian-file-cleaner-redux#70]
Similarly to Apple Notes, could there be an automatic delete of old trash files, e.g. older than 30 days old (ideally with 30 being configurable)?

**Comment by husjon** [comment]
Hmm, which kind of trash files are you refering to in this case?
Are you refering to files that have been deleted by the plugin and has been moved to System Trash or Obsidians internal trash (the `.trash` folder inside the Vault)?
If the former, I do not think I would be able to reach it from Application sandbox, the latter however I think could be possible.

**Comment by huyz** [comment]
The latter, the internal .trash folder

**Comment by husjon** [comment]
Alright, I need to check what is needed but definitely think it should be possible.

**Comment by huyz** [comment]
Sweet thanks!
