### ISSUE TITLE
List of files to delete goes beyond confirmation window

### ISSUE THREAD

**Issue by rawengine67** [husjon/obsidian-file-cleaner-redux#76]
the list of the unused files, waiting confirmation to be deleted, stands just in the middle of the space of the note, making it impossible to actually check the files.
![redux](https://github.com/user-attachments/assets/a8552aea-567d-49d1-ba18-918406f2726d)

**Comment by husjon** [comment]
Hi, I'm preparing a fix for this now.
The content will now be constrained to the window and a scrollbar for only the files and folders will be visible if there are a lot of entries to show.

The fix will be part of version 1.2.1 which will be released shortly.
This issue will be closed automatically when done.
